import pw from "playwright";
import { mkdir } from "node:fs/promises";
const { chromium, devices } = pw;
const out = process.argv[2];
await mkdir(out, { recursive: true });
const browser = await chromium.launch();
const context = await browser.newContext({ ...devices["iPhone 14"], deviceScaleFactor: 2, isMobile: true, hasTouch: true, colorScheme: "light", locale: "en-US", timezoneId: "America/New_York", geolocation: { latitude: 40.7074, longitude: -74.0113 }, permissions: ["geolocation"] });
await context.addInitScript(() => { try { localStorage.setItem("recall.token", "demo-token-for-screenshots"); localStorage.setItem("recall.installId", "demo-install"); } catch {} });
const page = await context.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
await page.goto("http://localhost:8080/map", { waitUntil: "networkidle" });
await page.waitForTimeout(3000);
await page.screenshot({ path: `${out}/15-map.png` });
const api = await (await fetch("http://localhost:4000/v1/restaurants/map?lat=40.7074&lng=-74.0113&radiusKm=1.5&discover=false", { headers: { authorization: "Bearer demo-token-for-screenshots" } })).json();
const ramen = api.items.find((i) => i.name === "Wall St Ramen");
await page.goto(`http://localhost:8080/restaurant/${ramen.profileId}`, { waitUntil: "networkidle" });
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/16-restaurant-public.png` });
await page.goto("http://localhost:8080/", { waitUntil: "networkidle" });
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/01-home.png` });
console.log("errors:", errors.join("\n") || "none");
await browser.close();
