/**
 * @recall/shared — types and validation schemas shared by the API and the mobile app.
 *
 * Everything that crosses the wire between client and server is defined here so both
 * sides agree on shapes at compile time and at runtime (zod).
 */
import { z } from "zod";

// ---------------------------------------------------------------------------
// Recall domain
// ---------------------------------------------------------------------------

/** Public data sources the ingestion service pulls from. */
export const RecallSource = z.enum(["FDA", "FSIS", "CPSC"]);
export type RecallSource = z.infer<typeof RecallSource>;

/** Coarse product category, normalised across sources. */
export const RecallCategory = z.enum([
  "food",
  "meat_poultry",
  "dietary_supplement",
  "cosmetic",
  "drug",
  "medical_device",
  "veterinary",
  "consumer_product",
  "other",
]);
export type RecallCategory = z.infer<typeof RecallCategory>;

/**
 * Normalised severity.
 *  - critical: FDA Class I / FSIS "High" risk / CPSC recall with death or serious injury
 *  - high:     FDA Class II / FSIS "Medium"
 *  - low:      FDA Class III / FSIS "Low" or "Marginal" / public health alert
 *  - unknown:  source did not classify
 */
export const RecallSeverity = z.enum(["critical", "high", "low", "unknown"]);
export type RecallSeverity = z.infer<typeof RecallSeverity>;

export const RecallStatus = z.enum(["ongoing", "completed", "terminated", "pending", "unknown"]);
export type RecallStatus = z.infer<typeof RecallStatus>;

/** A recall as served by the API (and stored, minus raw payload). */
export const Recall = z.object({
  id: z.string(),
  source: RecallSource,
  sourceId: z.string(),
  title: z.string(),
  summary: z.string(),
  productDescription: z.string(),
  reason: z.string(),
  category: RecallCategory,
  severity: RecallSeverity,
  status: RecallStatus,
  company: z.string(),
  brands: z.array(z.string()),
  upcs: z.array(z.string()),
  /** US state codes the product was distributed in; ["US"] when nationwide. */
  distributionStates: z.array(z.string()),
  recallDate: z.string().datetime().nullable(),
  publishedAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  url: z.string().url().nullable(),
  imageUrls: z.array(z.string()),
  /** Lot numbers, best-by dates, model numbers to compare against the package in hand. */
  codeInfo: z.string().nullable(),
  /** What to do: return for refund, discard, contact the firm… */
  remedy: z.string().nullable(),
});
export type Recall = z.infer<typeof Recall>;

export const RecallListQuery = z.object({
  q: z.string().trim().max(200).optional(),
  source: RecallSource.optional(),
  category: RecallCategory.optional(),
  severity: RecallSeverity.optional(),
  state: z.string().length(2).toUpperCase().optional(),
  since: z.string().datetime().optional(),
  cursor: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(25),
});
export type RecallListQuery = z.infer<typeof RecallListQuery>;

export const Paginated = <T extends z.ZodTypeAny>(item: T) =>
  z.object({ items: z.array(item), nextCursor: z.string().nullable() });

// ---------------------------------------------------------------------------
// Auth / devices
// ---------------------------------------------------------------------------

export const AnonymousAuthRequest = z.object({
  /** Stable per-install identifier generated by the app. */
  installId: z.string().min(8).max(128),
  platform: z.enum(["ios", "android", "web"]),
});
export type AnonymousAuthRequest = z.infer<typeof AnonymousAuthRequest>;

export const AuthResponse = z.object({
  token: z.string(),
  user: z.object({
    id: z.string(),
    tier: z.enum(["free", "premium"]),
    createdAt: z.string().datetime(),
  }),
});
export type AuthResponse = z.infer<typeof AuthResponse>;

/**
 * Coarse location report from the phone. We deliberately accept only a state (resolved
 * on-device by reverse geocoding), never coordinates, so the server cannot track users.
 */
export const UpdateLocationRequest = z.object({
  state: z.string().length(2).toUpperCase(),
  /** When true, also set this as the user's home state (first-run auto-detect or explicit choice). */
  setHome: z.boolean().default(false),
});
export type UpdateLocationRequest = z.infer<typeof UpdateLocationRequest>;

export const RegisterDeviceRequest = z.object({
  expoPushToken: z.string().regex(/^Expo(nent)?PushToken\[.+\]$/, "Must be an Expo push token"),
  platform: z.enum(["ios", "android", "web"]),
  /** Optional two-letter state used to down-rank recalls not distributed near the user. */
  homeState: z.string().length(2).toUpperCase().optional(),
});
export type RegisterDeviceRequest = z.infer<typeof RegisterDeviceRequest>;

// ---------------------------------------------------------------------------
// Watchlist
// ---------------------------------------------------------------------------

/**
 * What a user is watching.
 *  - product:    free text / brand ("Jif peanut butter", "Boar's Head")
 *  - upc:        barcode scanned or typed
 *  - scan:       OCR text captured from a physical label, with optional user context
 *  - restaurant: PREMIUM — a restaurant whose supply chain is researched by AI
 */
export const WatchItemKind = z.enum(["product", "upc", "scan", "restaurant", "category"]);
export type WatchItemKind = z.infer<typeof WatchItemKind>;

export const CreateWatchItemRequest = z.object({
  kind: WatchItemKind,
  /** Display label chosen by the user or derived from the input (defaults to the restaurant name for catalog picks). */
  label: z.string().trim().max(120).default(""),
  /** Search terms (brand, product name). Required for product/scan/restaurant. */
  terms: z.array(z.string().trim().min(2).max(80)).max(20).default([]),
  upc: z.string().regex(/^\d{8,14}$/).optional(),
  /** Free-form context: "bought at Costco 9/28", "for my kid's lunch", etc. */
  context: z.string().trim().max(500).optional(),
  /** Raw OCR text for `scan` items; kept so re-matching can run as recalls arrive. */
  ocrText: z.string().max(4000).optional(),
  /** Restaurant metadata (premium). */
  restaurant: z
    .object({
      name: z.string().trim().max(120).default(""),
      city: z.string().trim().max(80).optional(),
      state: z.string().length(2).toUpperCase().optional(),
      website: z.string().url().optional(),
      /** Venue coordinates (from the phone's location or a map pick). Enables geofence alerts. */
      latitude: z.number().min(-90).max(90).optional(),
      longitude: z.number().min(-180).max(180).optional(),
      /** Pick an existing catalog restaurant instead of describing one; other fields are then optional. */
      profileId: z.string().optional(),
    })
    .optional(),
  categories: z.array(RecallCategory).max(9).default([]),
  /** Category subscriptions only: ignore recalls below this severity. */
  minSeverity: RecallSeverity.optional(),
});
export type CreateWatchItemRequest = z.infer<typeof CreateWatchItemRequest>;

export const WatchItem = CreateWatchItemRequest.extend({
  id: z.string(),
  userId: z.string(),
  createdAt: z.string().datetime(),
  /** Set when the item came from a premium connector import (e.g. "instacart"). */
  importedFrom: z.string().nullable(),
  /** For restaurants: last AI research summary. */
  researchSummary: z.string().nullable(),
  researchUpdatedAt: z.string().datetime().nullable(),
});
export type WatchItem = z.infer<typeof WatchItem>;

// ---------------------------------------------------------------------------
// Alerts (matches between a user's watchlist and a recall)
// ---------------------------------------------------------------------------

export const MatchReason = z.enum([
  "upc_exact",
  "brand_match",
  "text_match",
  "scan_text_match",
  "restaurant_supplier",
  "category_subscription",
]);
export type MatchReason = z.infer<typeof MatchReason>;

export const Alert = z.object({
  id: z.string(),
  recall: Recall,
  watchItemId: z.string().nullable(),
  watchItemLabel: z.string().nullable(),
  reason: MatchReason,
  /** 0..1 confidence the recall concerns something the user cares about. */
  score: z.number().min(0).max(1),
  explanation: z.string(),
  createdAt: z.string().datetime(),
  readAt: z.string().datetime().nullable(),
  pushedAt: z.string().datetime().nullable(),
  dismissedAt: z.string().datetime().nullable(),
  dismissReason: z.enum(["dont_have", "false_match", "not_interested"]).nullable(),
  resolvedAt: z.string().datetime().nullable(),
  resolvedAction: z.enum(["discarded", "returned", "contacted", "checked_not_affected"]).nullable(),
});
export type Alert = z.infer<typeof Alert>;

export const DismissAlertRequest = z.object({ reason: z.enum(["dont_have", "false_match", "not_interested"]).default("dont_have") });
export type DismissAlertRequest = z.infer<typeof DismissAlertRequest>;
export const ResolveAlertRequest = z.object({ action: z.enum(["discarded", "returned", "contacted", "checked_not_affected"]) });
export type ResolveAlertRequest = z.infer<typeof ResolveAlertRequest>;

// ---------------------------------------------------------------------------
// Notification preferences
// ---------------------------------------------------------------------------

export const NotificationPreferences = z.object({
  /** Lowest severity that gets a push. "unknown" means everything. */
  pushMinSeverity: RecallSeverity,
  mutedCategories: z.array(RecallCategory),
  /** Local hours 0–23; pushes are held while within [start, end). Null disables. Wraps midnight. */
  quietHoursStart: z.number().int().min(0).max(23).nullable(),
  quietHoursEnd: z.number().int().min(0).max(23).nullable(),
  /** IANA zone, e.g. "America/Chicago". Sent by the phone. */
  timezone: z.string().max(64).nullable(),
  /** One daily summary instead of a push per alert. Critical alerts still go out at once. */
  digestMode: z.boolean(),
  digestHour: z.number().int().min(0).max(23),
});
export type NotificationPreferences = z.infer<typeof NotificationPreferences>;
export const UpdatePreferencesRequest = NotificationPreferences.partial();
export type UpdatePreferencesRequest = z.infer<typeof UpdatePreferencesRequest>;

// ---------------------------------------------------------------------------
// Scanning (OCR / barcode)
// ---------------------------------------------------------------------------

export const ScanMatchRequest = z.object({
  /** Text produced by on-device OCR, or a barcode value. */
  ocrText: z.string().max(4000).optional(),
  upc: z.string().regex(/^\d{8,14}$/).optional(),
  /** Optional user-supplied context ("this is a protein bar", "bought at Kroger"). */
  context: z.string().max(500).optional(),
  /** When true, also create a watch item so future recalls alert the user. */
  watch: z.boolean().default(false),
});
export type ScanMatchRequest = z.infer<typeof ScanMatchRequest>;

export const ScanMatch = z.object({
  recall: Recall,
  reason: MatchReason,
  score: z.number(),
  explanation: z.string(),
});
export type ScanMatch = z.infer<typeof ScanMatch>;

export const ScanMatchResponse = z.object({
  /** Normalised product guess derived from the text (brand + product terms). */
  extracted: z.object({ brand: z.string().nullable(), terms: z.array(z.string()), upc: z.string().nullable() }),
  matches: z.array(ScanMatch),
  watchItem: WatchItem.nullable(),
});
export type ScanMatchResponse = z.infer<typeof ScanMatchResponse>;

// --- Receipts -----------------------------------------------------------------

export const ReceiptScanRequest = z.object({
  /** OCR text of the receipt (on-device). */
  ocrText: z.string().min(3).max(12000).optional(),
  /** Premium: the receipt photo, so AI can decode lines OCR mangled. */
  imageBase64: z.string().min(100).optional(),
  mediaType: z.enum(["image/jpeg", "image/png", "image/webp"]).default("image/jpeg"),
  /** Add every parsed item to the watchlist. */
  watch: z.boolean().default(false),
  context: z.string().max(300).optional(),
});
export type ReceiptScanRequest = z.input<typeof ReceiptScanRequest>;

export const ReceiptItemStatus = z.enum(["recalled", "possible", "clear"]);
export type ReceiptItemStatus = z.infer<typeof ReceiptItemStatus>;

export const ReceiptItem = z.object({
  raw: z.string(),
  product: z.string(),
  brand: z.string().nullable(),
  terms: z.array(z.string()),
  status: ReceiptItemStatus,
  matches: z.array(ScanMatch),
  watchItemId: z.string().nullable(),
});
export type ReceiptItem = z.infer<typeof ReceiptItem>;

export const ReceiptScanResponse = z.object({
  id: z.string(),
  store: z.string().nullable(),
  purchasedAt: z.string().nullable(),
  items: z.array(ReceiptItem),
  flagged: z.number().int(),
  decodedByAi: z.boolean(),
  watched: z.boolean(),
  /** Items we could not read; shown so the user can type them in. */
  skippedLines: z.number().int(),
});
export type ReceiptScanResponse = z.infer<typeof ReceiptScanResponse>;

export const ReceiptSummary = z.object({
  id: z.string(),
  store: z.string().nullable(),
  purchasedAt: z.string().nullable(),
  itemCount: z.number().int(),
  flaggedCount: z.number().int(),
  watched: z.boolean(),
  createdAt: z.string().datetime(),
});
export type ReceiptSummary = z.infer<typeof ReceiptSummary>;

// ---------------------------------------------------------------------------
// Premium — AI connectors (MCP) and restaurant research
// ---------------------------------------------------------------------------

/** A remote MCP server the user has connected (grocery / delivery / shopping account). */
export const ConnectorProvider = z.enum(["instacart", "doordash", "ubereats", "amazon", "walmart", "kroger", "custom"]);
export type ConnectorProvider = z.infer<typeof ConnectorProvider>;

export const CreateConnectorRequest = z.object({
  provider: ConnectorProvider,
  displayName: z.string().trim().min(1).max(80),
  /** Remote MCP server URL (Streamable HTTP or SSE). */
  mcpUrl: z.string().url(),
  /** OAuth access token or API token for that MCP server. Stored encrypted. */
  authorizationToken: z.string().min(1).max(4096).optional(),
});
export type CreateConnectorRequest = z.infer<typeof CreateConnectorRequest>;

export const Connector = z.object({
  id: z.string(),
  provider: ConnectorProvider,
  displayName: z.string(),
  mcpUrl: z.string().url(),
  hasToken: z.boolean(),
  lastSyncAt: z.string().datetime().nullable(),
  lastSyncStatus: z.enum(["never", "ok", "error"]),
  lastSyncError: z.string().nullable(),
  createdAt: z.string().datetime(),
});
export type Connector = z.infer<typeof Connector>;

export const ImportPurchasesResponse = z.object({
  connectorId: z.string(),
  created: z.array(WatchItem),
  skippedDuplicates: z.number().int(),
  summary: z.string(),
});
export type ImportPurchasesResponse = z.infer<typeof ImportPurchasesResponse>;

/**
 * Research is done once per restaurant and shared by every user tracking it (see
 * `shared`). It is refreshed only when stale, so most restaurant adds are instant and free.
 */
export const RestaurantResearch = z.object({
  watchItemId: z.string(),
  restaurant: z.string(),
  summary: z.string(),
  /** Suppliers / brands / ingredients the research surfaced, now used as match terms. */
  supplierTerms: z.array(z.string()),
  /** Food-safety signals found in reviews / inspection data. */
  riskSignals: z.array(z.object({ signal: z.string(), sourceUrl: z.string().nullable() })),
  sources: z.array(z.string()),
  matchedRecalls: z.array(ScanMatch),
  researchedAt: z.string().datetime().nullable(),
  status: z.enum(["pending", "ready", "failed"]),
  error: z.string().nullable(),
  shared: z
    .object({
      profileId: z.string(),
      /** Watch items (across all users) linked to this restaurant. */
      trackedBy: z.number().int(),
      /** How many times the AI research has actually run. */
      researchCount: z.number().int(),
      /** How many times a user got the cached result instead. */
      cacheHits: z.number().int(),
      fresh: z.boolean(),
      canRefresh: z.boolean(),
    })
    .nullable(),
});

/** How a jurisdiction expresses inspection results. */
export const GradeScale = z.enum(["letter_abc", "score_100", "pass_fail", "nyc_points"]);
export type GradeScale = z.infer<typeof GradeScale>;

export const RestaurantGrade = z.object({
  grade: z.string().nullable(),
  score: z.number().int().nullable(),
  scale: GradeScale.nullable(),
  source: z.string().nullable(),
  lastInspectedAt: z.string().datetime().nullable(),
  checkedAt: z.string().datetime().nullable(),
  /** Plain-language reading: "A — excellent", "Fail — closed pending re-inspection"… */
  label: z.string().nullable(),
  /** good | ok | poor | unknown — for colouring. */
  level: z.enum(["good", "ok", "poor", "unknown"]),
});
export type RestaurantGrade = z.infer<typeof RestaurantGrade>;

export const Inspection = z.object({
  id: z.string(),
  inspectedAt: z.string().datetime(),
  grade: z.string().nullable(),
  score: z.number().int().nullable(),
  inspectionType: z.string().nullable(),
  violations: z.array(z.object({ code: z.string().nullable(), description: z.string(), critical: z.boolean() })),
  source: z.string(),
  sourceUrl: z.string().nullable(),
});
export type Inspection = z.infer<typeof Inspection>;

/** Something changed about a restaurant the user tracks (grade change, closure, research refresh). */
export const RestaurantNotice = z.object({
  id: z.string(),
  profileId: z.string(),
  restaurant: z.string(),
  watchItemId: z.string().nullable(),
  kind: z.enum(["grade_change", "grade_first", "closure", "research_updated"]),
  title: z.string(),
  body: z.string(),
  data: z.record(z.unknown()).nullable(),
  createdAt: z.string().datetime(),
  readAt: z.string().datetime().nullable(),
});
export type RestaurantNotice = z.infer<typeof RestaurantNotice>;

/** Catalog entry: a restaurant someone has already added, with its shared data. */
export const CatalogRestaurant = z.object({
  profileId: z.string(),
  name: z.string(),
  city: z.string().nullable(),
  state: z.string().nullable(),
  website: z.string().nullable(),
  latitude: z.number().nullable(),
  longitude: z.number().nullable(),
  distanceKm: z.number().nullable(),
  trackedBy: z.number().int(),
  researchStatus: z.enum(["pending", "researching", "ready", "failed"]),
  researchedAt: z.string().datetime().nullable(),
  grade: RestaurantGrade,
  activeRecalls: z.number().int(),
  watchItemId: z.string().nullable(),
});
export type CatalogRestaurant = z.infer<typeof CatalogRestaurant>;

/** 1–5 safety rating shown on the map: health grade first, then recall exposure. */
export const SafetyRating = z.object({
  stars: z.number().min(1).max(5).nullable(),
  reason: z.string(),
  level: z.enum(["good", "ok", "poor", "unknown"]),
});
export type SafetyRating = z.infer<typeof SafetyRating>;

/** A pin on the map. Free to view; tracking is premium. */
export const MapRestaurant = z.object({
  profileId: z.string(),
  name: z.string(),
  address: z.string().nullable(),
  city: z.string().nullable(),
  state: z.string().nullable(),
  latitude: z.number(),
  longitude: z.number(),
  distanceKm: z.number(),
  grade: RestaurantGrade,
  rating: SafetyRating,
  activeRecalls: z.number().int(),
  trackedBy: z.number().int(),
  /** Set when the current user tracks it. */
  watchItemId: z.string().nullable(),
});
export type MapRestaurant = z.infer<typeof MapRestaurant>;

export const MapResponse = z.object({
  items: z.array(MapRestaurant),
  /** Where the venues came from this time: open data pulled now, cached, or catalog only. */
  discovery: z.object({ source: z.string().nullable(), fetched: z.number().int(), cached: z.boolean() }),
  center: z.object({ latitude: z.number(), longitude: z.number() }),
  radiusKm: z.number(),
});
export type MapResponse = z.infer<typeof MapResponse>;

/** Public restaurant page (no research; that is premium). */
export const PublicRestaurant = z.object({
  profileId: z.string(),
  name: z.string(),
  address: z.string().nullable(),
  city: z.string().nullable(),
  state: z.string().nullable(),
  website: z.string().nullable(),
  latitude: z.number().nullable(),
  longitude: z.number().nullable(),
  grade: RestaurantGrade,
  rating: SafetyRating,
  inspections: z.array(Inspection),
  activeRecalls: z.number().int(),
  matchedRecalls: z.array(ScanMatch),
  trackedBy: z.number().int(),
  watchItemId: z.string().nullable(),
  researched: z.boolean(),
});
export type PublicRestaurant = z.infer<typeof PublicRestaurant>;

/** A known restaurant near the user, with whether its suppliers currently have recalls. */
export const NearbyRestaurant = z.object({
  profileId: z.string(),
  name: z.string(),
  city: z.string().nullable(),
  state: z.string().nullable(),
  latitude: z.number(),
  longitude: z.number(),
  distanceKm: z.number(),
  trackedBy: z.number().int(),
  researchStatus: z.enum(["pending", "researching", "ready", "failed"]),
  summary: z.string().nullable(),
  /** Recalls in the last 180 days matching this restaurant's suppliers. */
  activeRecalls: z.number().int(),
  /** Whether the current user already tracks it (and the watch item id). */
  watchItemId: z.string().nullable(),
  grade: RestaurantGrade,
});
export type NearbyRestaurant = z.infer<typeof NearbyRestaurant>;

export const RestaurantLookup = z.object({
  known: z.boolean(),
  profileId: z.string().optional(),
  status: z.enum(["pending", "researching", "ready", "failed"]).optional(),
  fresh: z.boolean().optional(),
  researchedAt: z.string().datetime().nullable().optional(),
  trackedBy: z.number().int().optional(),
  summary: z.string().nullable().optional(),
});
export type RestaurantLookup = z.infer<typeof RestaurantLookup>;

export const CreateWatchItemResponse = z.object({
  item: WatchItem,
  matches: z.array(ScanMatch),
  researchQueued: z.boolean(),
  /** Present for restaurant items: whether cached research was reused or new research was queued. */
  research: z.object({ status: z.enum(["cached", "queued", "unavailable"]), profileId: z.string(), researchedAt: z.string().datetime().nullable() }).nullable(),
});
export type CreateWatchItemResponse = z.infer<typeof CreateWatchItemResponse>;
export type RestaurantResearch = z.infer<typeof RestaurantResearch>;

export const PremiumStatus = z.object({
  tier: z.enum(["free", "premium"]),
  features: z.object({
    connectors: z.boolean(),
    restaurants: z.boolean(),
    aiScan: z.boolean(),
  }),
  expiresAt: z.string().datetime().nullable(),
});
export type PremiumStatus = z.infer<typeof PremiumStatus>;

// ---------------------------------------------------------------------------
// Misc
// ---------------------------------------------------------------------------

export const ApiError = z.object({
  error: z.string(),
  message: z.string(),
  code: z.string().optional(),
});
export type ApiError = z.infer<typeof ApiError>;

export const US_STATES = [
  "AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD",
  "MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC",
  "SD","TN","TX","UT","VT","VA","WA","WV","WI","WY","DC","PR",
] as const;

export const SEVERITY_LABEL: Record<RecallSeverity, string> = {
  critical: "Critical — serious health risk",
  high: "High — may cause temporary or reversible harm",
  low: "Low — unlikely to cause harm",
  unknown: "Unclassified",
};

export const CATEGORY_LABEL: Record<RecallCategory, string> = {
  food: "Food",
  meat_poultry: "Meat, poultry & eggs",
  dietary_supplement: "Supplements",
  cosmetic: "Cosmetics",
  drug: "Drugs",
  medical_device: "Medical devices",
  veterinary: "Pet & veterinary",
  consumer_product: "Consumer products",
  other: "Other",
};
